##
# .travis.yml
# -----------
# @author brikcss
# @homepage https://github.com/brikcss
# @description Configuration file for [TravisCI](https://travis-ci.org/).
# ---------------------------------------------------------------------
##


language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  email:
    on_failure: always
node_js: '8'
env: BUILD_LEADER_ID=3 NODE_ENV=prod

jobs:
  include:
    - stage: build
      node_js:
        - '8'
        - '9'
      before_script: npm prune -d
      script: npm run test -d
    - stage: release
      node_js: '9'
      before_script: npm prune -d
      script: echo 'Preparing for release...'
      after_script: npm run release -d
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
